### ISSUE TITLE
RandomRectangles.py

### ISSUE THREAD

**Issue by AmusedNetwork** [The-Penultimate-Defenestrator/Python#1]
Not random enough. The rectangles always seem to be more concentrated in the bottom right corner!
![screen shot 2016-08-14 at 22 33 57](https://cloud.githubusercontent.com/assets/5558617/17652243/381b19fc-626f-11e6-8ee4-2711beabbe13.png)

**Comment by controversial** [comment]
This was literally the very first thing I wrote in Python ever, and I don't
really care. Thanks, though 😉

**Comment by JosephBywater** [comment]
👌
